matrix:
  include:
  - language: go
    sudo: required
    services:
    - docker
    script:
    - export GO111MODULE=on
    - go mod vendor
    - make build
    - test -f bin/linux_amd64/honeypot
    - make all-container
    - docker images | grep "^docker.pkg.github.com/kyberorg/honeypot/honeypot.*__linux_amd64"
    - make test
  - language: go
    addons:
      sonarcloud:
        organization: kyberorg
        token:
          secure: fV8p83gaDNUamGYZZOmJiIenRo/1sTBxQs/6dkzauBIn6YI5v7xZJqI4j1ibID12TXaQQoHIlGDsoaNQbJQXHINaIah5C4BIK6GORbM1ElJpzPaa87zkC9Fpm68DVigJSthFz6IwYxQn2zlxYeN6xkcxBo/9OlnPKDJ06QpqQYdkyPvI5nYAcM0wQ0Yrw04mONFjQnQcMDuo4O+F/SZsRYFmda5p4waPbFSKOExmGmQS/vftCeaXge0u6fm7LpW87ixdYWYMgkjXu5D8NuqA/9WdLSVLi/YpnnU7J/DOtNeh2UFf4F7X4cB3mwULu88GuJocHbruC9vt2t0BbWy0rGBmjVrze7EjWKSzs5ASbsj6qflGtt13OxGTzJAEP0FV1Ikcr3xikUG6798IBDk2HGnggtPE2US9EpUI3QsfGrOzRIfv3l67SHUv8Wc1ks8HT9tXoX9blJN2mP7CPDjaNEvkHzkGviJPg381mT5QYbSx5bqYUkGdUxGRNk/YtP1J+i8N895N8NQpjy7uTGILafCR0ahEYb3ZQg96UU/l9IvriaxM/pZPlj0ADHry6dDbWHguS4txp+7AmxMFOq77ez76f82OFZ9iDl0dwFeQEun10zH9IL0LqrXeno+Fz0dg+ykOlSUcnlUDSNIsBRjB4UgY+umtqyNlxR84FDACpXY=
    before_script:
    - "./reports.sh"
    - export GO111MODULE=on
    - go mod vendor
    - make ci
    script:
    - sonar-scanner
  - language: go
    before_script:
    - "./reports.sh"
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
      > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - "./cc-test-reporter before-build"
    script:
    - export GO111MODULE=on
    - go mod vendor
    - make ci
    after_script:
    - "./cc-test-reporter after-build -t gocov --exit-code $TRAVIS_TEST_RESULT"
  - language: go
    services:
    - docker
    if: branch = trunk
    script:
    - export GO111MODULE=on
    - go mod vendor
    - echo "$DOCKER_PASSWORD" | docker login docker.pkg.github.com -u "$DOCKER_USERNAME"
      --password-stdin
    - make container
    - make push
notifications:
  email: false
env:
  global:
    secure: fV8p83gaDNUamGYZZOmJiIenRo/1sTBxQs/6dkzauBIn6YI5v7xZJqI4j1ibID12TXaQQoHIlGDsoaNQbJQXHINaIah5C4BIK6GORbM1ElJpzPaa87zkC9Fpm68DVigJSthFz6IwYxQn2zlxYeN6xkcxBo/9OlnPKDJ06QpqQYdkyPvI5nYAcM0wQ0Yrw04mONFjQnQcMDuo4O+F/SZsRYFmda5p4waPbFSKOExmGmQS/vftCeaXge0u6fm7LpW87ixdYWYMgkjXu5D8NuqA/9WdLSVLi/YpnnU7J/DOtNeh2UFf4F7X4cB3mwULu88GuJocHbruC9vt2t0BbWy0rGBmjVrze7EjWKSzs5ASbsj6qflGtt13OxGTzJAEP0FV1Ikcr3xikUG6798IBDk2HGnggtPE2US9EpUI3QsfGrOzRIfv3l67SHUv8Wc1ks8HT9tXoX9blJN2mP7CPDjaNEvkHzkGviJPg381mT5QYbSx5bqYUkGdUxGRNk/YtP1J+i8N895N8NQpjy7uTGILafCR0ahEYb3ZQg96UU/l9IvriaxM/pZPlj0ADHry6dDbWHguS4txp+7AmxMFOq77ez76f82OFZ9iDl0dwFeQEun10zH9IL0LqrXeno+Fz0dg+ykOlSUcnlUDSNIsBRjB4UgY+umtqyNlxR84FDACpXY=
