name: Development Automatization

on:
  push:
    branches-ignore:
      - trunk

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build docker image (tag 'latest')
        run: make docker-build DOCKER_REPO=ghcr.io/kyberorg/honeypot DOCKER_TAG=latest

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to Docker Hub (tag 'latest')
        run: make docker-push DOCKER_REPO=ghcr.io/kyberorg/honeypot DOCKER_TAG=latest

  binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Make Binary
        run: make binary

      - name: Publish
        uses: skx/github-action-publish-binaries@release-0.15
        with:
          args: 'bin/honeypot'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
